/**
 * Seed script — adds dummy items and loads to Firestore.
 *
 * Usage (call from browser console or a dev-only button):
 *   import { seedAll } from "@/constants/scripts";
 *   await seedAll();
 */

import { collection, addDoc, serverTimestamp } from "firebase/firestore";
import { db } from "@/lib/firebase";

const ITEMS_COL = "items";
const LOADS_COL = "loads";

// ── Item seed data (100 items) ─────────────────────────────────────────────────

const RAW_ITEMS = [
  // Engine parts (15)
  {
    item_no: "ITM-001",
    name: "Oil Filter",
    type: "Engine",
    quantity: 50,
    rack_no: "R-01",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-002",
    name: "Air Filter",
    type: "Engine",
    quantity: 30,
    rack_no: "R-01",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-003",
    name: "Fuel Filter",
    type: "Engine",
    quantity: 40,
    rack_no: "R-01",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-004",
    name: "Drive Belt",
    type: "Engine",
    quantity: 25,
    rack_no: "R-01",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-005",
    name: "Radiator Cap",
    type: "Engine",
    quantity: 20,
    rack_no: "R-02",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-006",
    name: "Engine Gasket",
    type: "Engine",
    quantity: 15,
    rack_no: "R-02",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-007",
    name: "Spark Plug",
    type: "Engine",
    quantity: 80,
    rack_no: "R-02",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-008",
    name: "Piston Ring Set",
    type: "Engine",
    quantity: 10,
    rack_no: "R-02",
    returnable: false,
    vehicle_type: null,
    status: "pending",
  },
  {
    item_no: "ITM-009",
    name: "Alternator Belt",
    type: "Engine",
    quantity: 20,
    rack_no: "R-03",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-010",
    name: "Water Pump",
    type: "Engine",
    quantity: 8,
    rack_no: "R-03",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-011",
    name: "Engine Oil Can (5L)",
    type: "Engine",
    quantity: 100,
    rack_no: "R-03",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-012",
    name: "Coolant Bottle (1L)",
    type: "Engine",
    quantity: 60,
    rack_no: "R-03",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-013",
    name: "Fuel Pump",
    type: "Engine",
    quantity: 12,
    rack_no: "R-04",
    returnable: true,
    vehicle_type: null,
    status: "pending",
  },
  {
    item_no: "ITM-014",
    name: "Thermostat",
    type: "Engine",
    quantity: 15,
    rack_no: "R-04",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-015",
    name: "Timing Belt",
    type: "Engine",
    quantity: 10,
    rack_no: "R-04",
    returnable: false,
    vehicle_type: null,
  },

  // Ammunition (15)
  {
    item_no: "ITM-016",
    name: "7.62×39mm Round",
    type: "Ammunition",
    quantity: 5000,
    rack_no: "R-05",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-017",
    name: "5.56×45mm Round",
    type: "Ammunition",
    quantity: 3000,
    rack_no: "R-05",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-018",
    name: "9×19mm Round",
    type: "Ammunition",
    quantity: 2000,
    rack_no: "R-05",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-019",
    name: "12-Gauge Shell",
    type: "Ammunition",
    quantity: 500,
    rack_no: "R-05",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-020",
    name: ".50 BMG Round",
    type: "Ammunition",
    quantity: 1000,
    rack_no: "R-06",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-021",
    name: "40mm Grenade Round",
    type: "Ammunition",
    quantity: 200,
    rack_no: "R-06",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-022",
    name: "RPG Warhead",
    type: "Ammunition",
    quantity: 50,
    rack_no: "R-06",
    returnable: false,
    vehicle_type: null,
    status: "pending",
  },
  {
    item_no: "ITM-023",
    name: "81mm Mortar Round",
    type: "Ammunition",
    quantity: 100,
    rack_no: "R-06",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-024",
    name: "120mm Mortar Round",
    type: "Ammunition",
    quantity: 60,
    rack_no: "R-07",
    returnable: false,
    vehicle_type: null,
    status: "pending",
  },
  {
    item_no: "ITM-025",
    name: "60mm Mortar Round",
    type: "Ammunition",
    quantity: 150,
    rack_no: "R-07",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-026",
    name: "Signal Flare",
    type: "Ammunition",
    quantity: 80,
    rack_no: "R-07",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-027",
    name: "Smoke Grenade",
    type: "Ammunition",
    quantity: 120,
    rack_no: "R-07",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-028",
    name: "Fragmentation Grenade",
    type: "Ammunition",
    quantity: 200,
    rack_no: "R-08",
    returnable: false,
    vehicle_type: null,
    status: "pending",
  },
  {
    item_no: "ITM-029",
    name: "Illumination Round",
    type: "Ammunition",
    quantity: 40,
    rack_no: "R-08",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-030",
    name: "Tracer Round 7.62mm",
    type: "Ammunition",
    quantity: 1000,
    rack_no: "R-08",
    returnable: false,
    vehicle_type: null,
  },

  // Tools (10)
  {
    item_no: "ITM-031",
    name: "Wrench Set",
    type: "Tools",
    quantity: 20,
    rack_no: "R-09",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-032",
    name: "Screwdriver Kit",
    type: "Tools",
    quantity: 25,
    rack_no: "R-09",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-033",
    name: "Socket Set",
    type: "Tools",
    quantity: 15,
    rack_no: "R-09",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-034",
    name: "Hammer",
    type: "Tools",
    quantity: 30,
    rack_no: "R-09",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-035",
    name: "Torque Wrench",
    type: "Tools",
    quantity: 10,
    rack_no: "R-10",
    returnable: true,
    vehicle_type: null,
    status: "pending",
  },
  {
    item_no: "ITM-036",
    name: "Pliers Set",
    type: "Tools",
    quantity: 20,
    rack_no: "R-10",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-037",
    name: "Wire Cutter",
    type: "Tools",
    quantity: 15,
    rack_no: "R-10",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-038",
    name: "Drill Bit Set",
    type: "Tools",
    quantity: 12,
    rack_no: "R-10",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-039",
    name: "Cable Tie Pack (100)",
    type: "Tools",
    quantity: 100,
    rack_no: "R-11",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-040",
    name: "Duct Tape Roll",
    type: "Tools",
    quantity: 50,
    rack_no: "R-11",
    returnable: false,
    vehicle_type: null,
  },

  // Medical (10)
  {
    item_no: "ITM-041",
    name: "Bandage Roll",
    type: "Medical",
    quantity: 200,
    rack_no: "R-11",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-042",
    name: "Tourniquet",
    type: "Medical",
    quantity: 100,
    rack_no: "R-11",
    returnable: true,
    vehicle_type: null,
    status: "pending",
  },
  {
    item_no: "ITM-043",
    name: "Saline Solution",
    type: "Medical",
    quantity: 60,
    rack_no: "R-12",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-044",
    name: "Antiseptic Wipes",
    type: "Medical",
    quantity: 500,
    rack_no: "R-12",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-045",
    name: "Pain Reliever (Strip)",
    type: "Medical",
    quantity: 300,
    rack_no: "R-12",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-046",
    name: "Medical Tape",
    type: "Medical",
    quantity: 150,
    rack_no: "R-12",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-047",
    name: "Gauze Pad",
    type: "Medical",
    quantity: 400,
    rack_no: "R-13",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-048",
    name: "Splint",
    type: "Medical",
    quantity: 40,
    rack_no: "R-13",
    returnable: true,
    vehicle_type: null,
    status: "pending",
  },
  {
    item_no: "ITM-049",
    name: "Thermal Blanket",
    type: "Medical",
    quantity: 80,
    rack_no: "R-13",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-050",
    name: "IV Bag (500ml)",
    type: "Medical",
    quantity: 50,
    rack_no: "R-13",
    returnable: false,
    vehicle_type: null,
    status: "pending",
  },

  // Uniform (10)
  {
    item_no: "ITM-051",
    name: "Combat Boots",
    type: "Uniform",
    quantity: 100,
    rack_no: "R-14",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-052",
    name: "Helmet Liner",
    type: "Uniform",
    quantity: 80,
    rack_no: "R-14",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-053",
    name: "Combat Gloves",
    type: "Uniform",
    quantity: 150,
    rack_no: "R-14",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-054",
    name: "Balaclava",
    type: "Uniform",
    quantity: 120,
    rack_no: "R-14",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-055",
    name: "Knee Pad Set",
    type: "Uniform",
    quantity: 100,
    rack_no: "R-15",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-056",
    name: "Elbow Pad Set",
    type: "Uniform",
    quantity: 100,
    rack_no: "R-15",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-057",
    name: "Combat Belt",
    type: "Uniform",
    quantity: 90,
    rack_no: "R-15",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-058",
    name: "Tactical Vest",
    type: "Uniform",
    quantity: 60,
    rack_no: "R-15",
    returnable: true,
    vehicle_type: null,
    status: "pending",
  },
  {
    item_no: "ITM-059",
    name: "Boot Laces (Pair)",
    type: "Uniform",
    quantity: 200,
    rack_no: "R-16",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-060",
    name: "Boot Polish Tin",
    type: "Uniform",
    quantity: 100,
    rack_no: "R-16",
    returnable: false,
    vehicle_type: null,
  },

  // Electronics (10)
  {
    item_no: "ITM-061",
    name: "Radio Battery",
    type: "Electronics",
    quantity: 200,
    rack_no: "R-16",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-062",
    name: "Night Vision Battery",
    type: "Electronics",
    quantity: 100,
    rack_no: "R-16",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-063",
    name: "GPS Battery",
    type: "Electronics",
    quantity: 150,
    rack_no: "R-17",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-064",
    name: "Torch Battery (AA)",
    type: "Electronics",
    quantity: 300,
    rack_no: "R-17",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-065",
    name: "Flashlight",
    type: "Electronics",
    quantity: 80,
    rack_no: "R-17",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-066",
    name: "Signal Mirror",
    type: "Electronics",
    quantity: 40,
    rack_no: "R-17",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-067",
    name: "Solar Charger",
    type: "Electronics",
    quantity: 20,
    rack_no: "R-18",
    returnable: true,
    vehicle_type: null,
    status: "pending",
  },
  {
    item_no: "ITM-068",
    name: "USB-C Cable",
    type: "Electronics",
    quantity: 100,
    rack_no: "R-18",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-069",
    name: "Thermal Battery",
    type: "Electronics",
    quantity: 60,
    rack_no: "R-18",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-070",
    name: "Emergency Radio",
    type: "Electronics",
    quantity: 15,
    rack_no: "R-18",
    returnable: true,
    vehicle_type: null,
    status: "pending",
  },

  // Optical (10)
  {
    item_no: "ITM-071",
    name: "Lens Cleaning Kit",
    type: "Optical",
    quantity: 50,
    rack_no: "R-19",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-072",
    name: "Scope Cover",
    type: "Optical",
    quantity: 40,
    rack_no: "R-19",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-073",
    name: "Binocular Strap",
    type: "Optical",
    quantity: 30,
    rack_no: "R-19",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-074",
    name: "Night Vision Tube",
    type: "Optical",
    quantity: 10,
    rack_no: "R-19",
    returnable: true,
    vehicle_type: null,
    status: "pending",
  },
  {
    item_no: "ITM-075",
    name: "Thermal Lens",
    type: "Optical",
    quantity: 8,
    rack_no: "R-20",
    returnable: true,
    vehicle_type: null,
    status: "pending",
  },
  {
    item_no: "ITM-076",
    name: "Scope Mount",
    type: "Optical",
    quantity: 25,
    rack_no: "R-20",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-077",
    name: "Red Dot Sight",
    type: "Optical",
    quantity: 20,
    rack_no: "R-20",
    returnable: true,
    vehicle_type: null,
    status: "pending",
  },
  {
    item_no: "ITM-078",
    name: "3× Magnifier",
    type: "Optical",
    quantity: 15,
    rack_no: "R-20",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-079",
    name: "Laser Pointer",
    type: "Optical",
    quantity: 12,
    rack_no: "R-17",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-080",
    name: "Iron Sight Set",
    type: "Optical",
    quantity: 40,
    rack_no: "R-17",
    returnable: true,
    vehicle_type: null,
  },

  // Communication (10)
  {
    item_no: "ITM-081",
    name: "Headset",
    type: "Communication",
    quantity: 40,
    rack_no: "R-04",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-082",
    name: "Short Antenna",
    type: "Communication",
    quantity: 30,
    rack_no: "R-04",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-083",
    name: "Long Antenna",
    type: "Communication",
    quantity: 20,
    rack_no: "R-08",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-084",
    name: "PTT Button",
    type: "Communication",
    quantity: 50,
    rack_no: "R-08",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-085",
    name: "Radio Pouch",
    type: "Communication",
    quantity: 35,
    rack_no: "R-11",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-086",
    name: "Cable Assembly",
    type: "Communication",
    quantity: 25,
    rack_no: "R-11",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-087",
    name: "Encryption Key Card",
    type: "Communication",
    quantity: 10,
    rack_no: "R-15",
    returnable: true,
    vehicle_type: null,
    status: "pending",
  },
  {
    item_no: "ITM-088",
    name: "Speaker Mic",
    type: "Communication",
    quantity: 30,
    rack_no: "R-15",
    returnable: true,
    vehicle_type: null,
  },
  {
    item_no: "ITM-089",
    name: "Battery Charger",
    type: "Communication",
    quantity: 20,
    rack_no: "R-18",
    returnable: true,
    vehicle_type: null,
    status: "pending",
  },
  {
    item_no: "ITM-090",
    name: "Frequency Card",
    type: "Communication",
    quantity: 50,
    rack_no: "R-18",
    returnable: false,
    vehicle_type: null,
  },

  // Fuel & Lubricants (10)
  {
    item_no: "ITM-091",
    name: "Engine Oil (5L)",
    type: "Fuel",
    quantity: 80,
    rack_no: "R-03",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-092",
    name: "Gear Oil (5L)",
    type: "Fuel",
    quantity: 40,
    rack_no: "R-03",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-093",
    name: "Brake Fluid",
    type: "Fuel",
    quantity: 30,
    rack_no: "R-06",
    returnable: false,
    vehicle_type: null,
    status: "pending",
  },
  {
    item_no: "ITM-094",
    name: "Power Steering Fluid",
    type: "Fuel",
    quantity: 25,
    rack_no: "R-06",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-095",
    name: "Hydraulic Oil (5L)",
    type: "Fuel",
    quantity: 35,
    rack_no: "R-09",
    returnable: false,
    vehicle_type: null,
    status: "pending",
  },
  {
    item_no: "ITM-096",
    name: "Transmission Fluid",
    type: "Fuel",
    quantity: 30,
    rack_no: "R-09",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-097",
    name: "Grease Cartridge",
    type: "Fuel",
    quantity: 60,
    rack_no: "R-12",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-098",
    name: "Chain Lubricant",
    type: "Fuel",
    quantity: 40,
    rack_no: "R-12",
    returnable: false,
    vehicle_type: null,
  },
  {
    item_no: "ITM-099",
    name: "Contact Cleaner Spray",
    type: "Fuel",
    quantity: 20,
    rack_no: "R-15",
    returnable: false,
    vehicle_type: null,
    status: "pending",
  },
  {
    item_no: "ITM-100",
    name: "Penetrating Oil",
    type: "Fuel",
    quantity: 35,
    rack_no: "R-15",
    returnable: false,
    vehicle_type: null,
  },
];

// ── Load seed data (48 loads — 12 per category) ────────────────────────────────

const RAW_LOADS = [
  // ── Vehicle (12) ────────────────────────────────────────────────────────────
  {
    catalog_no: "VEH-001",
    name: "T-72",
    category: "Vehicle",
    catalog_type: "Tank",
    unit: "1 Armd Regt",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "Main battle tank, 125mm smoothbore gun",
  },
  {
    catalog_no: "VEH-002",
    name: "T-55",
    category: "Vehicle",
    catalog_type: "Tank",
    unit: "2 Armd Regt",
    blr_count: 1,
    ber: false,
    description: "Medium battle tank, requires suspension overhaul",
    status: "pending",
  },
  {
    catalog_no: "VEH-003",
    name: "T-59",
    category: "Vehicle",
    catalog_type: "Tank",
    unit: "3 Armd Regt",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "Chinese variant of T-54, operational",
  },
  {
    catalog_no: "VEH-004",
    name: "BMP-2",
    category: "Vehicle",
    catalog_type: "APC",
    unit: "1 Mech Bn",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "Infantry fighting vehicle, 30mm autocannon",
  },
  {
    catalog_no: "VEH-005",
    name: "M113",
    category: "Vehicle",
    catalog_type: "APC",
    unit: "2 Mech Bn",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "Aluminium-hulled APC, 12.7mm HMG",
  },
  {
    catalog_no: "VEH-006",
    name: "BTR-60",
    category: "Vehicle",
    catalog_type: "APC",
    unit: "3 Mech Bn",
    blr_count: 1,
    ber: false,
    description: "8-wheeled APC, engine needs replacement",
    status: "pending",
  },
  {
    catalog_no: "VEH-007",
    name: "Land Rover Defender",
    category: "Vehicle",
    catalog_type: "Jeep",
    unit: "1 Recce Sqn",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "4x4 utility vehicle",
  },
  {
    catalog_no: "VEH-008",
    name: "Toyota Hilux",
    category: "Vehicle",
    catalog_type: "Jeep",
    unit: "2 Recce Sqn",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "Armed pickup truck, .50 cal mount",
  },
  {
    catalog_no: "VEH-009",
    name: "UAZ-469",
    category: "Vehicle",
    catalog_type: "Jeep",
    unit: "1 Log Bn",
    blr: false,
    ber_count: 1,
    description: "Russian light utility vehicle, BER — chassis damage",
    status: "pending",
  },
  {
    catalog_no: "VEH-010",
    name: "Bedford MK",
    category: "Vehicle",
    catalog_type: "Truck",
    unit: "1 Tpt Coy",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "4-ton cargo truck, 4x4",
  },
  {
    catalog_no: "VEH-011",
    name: "MAN SX45",
    category: "Vehicle",
    catalog_type: "Truck",
    unit: "2 Tpt Coy",
    blr_count: 1,
    ber: false,
    description: "8x8 heavy truck, gearbox issue",
    status: "pending",
  },
  {
    catalog_no: "VEH-012",
    name: "ZIL-131",
    category: "Vehicle",
    catalog_type: "Truck",
    unit: "1 Engr Bn",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "Soviet 3.5-ton 6x6 cargo truck",
  },

  // ── Gun (12) ────────────────────────────────────────────────────────────────
  {
    catalog_no: "GUN-001",
    name: "AK-47",
    category: "Gun",
    catalog_type: "Assault Rifle",
    unit: "1 Inf Bn",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "7.62×39mm, selective fire assault rifle",
  },
  {
    catalog_no: "GUN-002",
    name: "AK-74",
    category: "Gun",
    catalog_type: "Assault Rifle",
    unit: "2 Inf Bn",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "5.45×39mm, improved AK platform",
  },
  {
    catalog_no: "GUN-003",
    name: "G3A3",
    category: "Gun",
    catalog_type: "Battle Rifle",
    unit: "3 Inf Bn",
    blr_count: 1,
    ber: false,
    description: "7.62×51mm NATO, gas-delayed blowback, trigger group BLR",
    status: "pending",
  },
  {
    catalog_no: "GUN-004",
    name: "M16A2",
    category: "Gun",
    catalog_type: "Assault Rifle",
    unit: "4 Inf Bn",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "5.56×45mm NATO, semi/burst fire",
  },
  {
    catalog_no: "GUN-005",
    name: "PKM",
    category: "Gun",
    catalog_type: "Machine Gun",
    unit: "1 Sp Wpn Pl",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "7.62×54mmR, general purpose machine gun",
  },
  {
    catalog_no: "GUN-006",
    name: "RPK-74",
    category: "Gun",
    catalog_type: "Machine Gun",
    unit: "2 Sp Wpn Pl",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "5.45×39mm, squad automatic weapon",
  },
  {
    catalog_no: "GUN-007",
    name: "DShK 1938",
    category: "Gun",
    catalog_type: "Heavy MG",
    unit: "1 Armd Regt",
    blr_count: 1,
    ber: false,
    description: "12.7×108mm HMG, pintle mount, BLR barrel worn",
    status: "pending",
  },
  {
    catalog_no: "GUN-008",
    name: "SVD Dragunov",
    category: "Gun",
    catalog_type: "Sniper Rifle",
    unit: "1 Recce Sqn",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "7.62×54mmR, semi-automatic sniper rifle",
  },
  {
    catalog_no: "GUN-009",
    name: "SSG-69",
    category: "Gun",
    catalog_type: "Sniper Rifle",
    unit: "2 Recce Sqn",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: ".308 Win bolt-action sniper rifle",
  },
  {
    catalog_no: "GUN-010",
    name: "Glock 17",
    category: "Gun",
    catalog_type: "Pistol",
    unit: "1 MP Coy",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "9×19mm, standard issue sidearm",
  },
  {
    catalog_no: "GUN-011",
    name: "TT-33",
    category: "Gun",
    catalog_type: "Pistol",
    unit: "2 MP Coy",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "7.62×25mm Tokarev pistol",
  },
  {
    catalog_no: "GUN-012",
    name: "SPAS-12",
    category: "Gun",
    catalog_type: "Shotgun",
    unit: "1 MP Coy",
    blr_count: 1,
    ber: false,
    description: "12-gauge semi/pump shotgun, stock mechanism BLR",
    status: "pending",
  },

  // ── Equipment (12) ───────────────────────────────────────────────────────────
  {
    catalog_no: "EQP-001",
    name: "Harris RF-7800",
    category: "Equipment",
    catalog_type: "Radio",
    unit: "1 Sigs Regt",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "Wideband networking radio, HF/VHF/UHF",
  },
  {
    catalog_no: "EQP-002",
    name: "SINCGARS RT-1523",
    category: "Equipment",
    catalog_type: "Radio",
    unit: "2 Sigs Regt",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "Single-channel ground/airborne radio",
  },
  {
    catalog_no: "EQP-003",
    name: "Motorola APX-8000",
    category: "Equipment",
    catalog_type: "Radio",
    unit: "3 Sigs Regt",
    blr_count: 1,
    ber: false,
    description: "Portable P25 radio, display cracked",
    status: "pending",
  },
  {
    catalog_no: "EQP-004",
    name: "PVS-14 NVG",
    category: "Equipment",
    catalog_type: "Night Vision",
    unit: "1 Recce Sqn",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "Gen 3 monocular night vision device",
  },
  {
    catalog_no: "EQP-005",
    name: "PVS-7D NVG",
    category: "Equipment",
    catalog_type: "Night Vision",
    unit: "2 Recce Sqn",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "Gen 2+ binocular night vision goggles",
  },
  {
    catalog_no: "EQP-006",
    name: "FLIR Scout TS",
    category: "Equipment",
    catalog_type: "Thermal",
    unit: "1 Recce Sqn",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "Handheld thermal imager, 240×180 resolution",
  },
  {
    catalog_no: "EQP-007",
    name: "Garmin GPSMAP",
    category: "Equipment",
    catalog_type: "Navigation",
    unit: "1 Log Bn",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "Handheld GPS navigator, topographic maps",
  },
  {
    catalog_no: "EQP-008",
    name: "Magellan MilSpec GPS",
    category: "Equipment",
    catalog_type: "Navigation",
    unit: "2 Log Bn",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "Military-grade GPS receiver",
  },
  {
    catalog_no: "EQP-009",
    name: "PASGT Vest",
    category: "Equipment",
    catalog_type: "Body Armor",
    unit: "1 Inf Bn",
    blr_count: 1,
    ber: false,
    description: "Personal armour system, Kevlar panels",
    status: "pending",
  },
  {
    catalog_no: "EQP-010",
    name: "IOTV Gen III",
    category: "Equipment",
    catalog_type: "Body Armor",
    unit: "2 Inf Bn",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "Improved outer tactical vest, ESAPI compatible",
  },
  {
    catalog_no: "EQP-011",
    name: "Claymore M18A1",
    category: "Equipment",
    catalog_type: "Mine",
    unit: "1 Engr Bn",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "Directional fragmentation mine",
  },
  {
    catalog_no: "EQP-012",
    name: "AN/PRC-152",
    category: "Equipment",
    catalog_type: "Radio",
    unit: "4 Sigs Regt",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "Multiband handheld radio, SATCOM capable",
  },

  // ── Weapon (12) ──────────────────────────────────────────────────────────────
  {
    catalog_no: "WPN-001",
    name: "RPG-7",
    category: "Weapon",
    catalog_type: "Rocket Launcher",
    unit: "1 Inf Bn",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "85mm anti-tank rocket launcher",
  },
  {
    catalog_no: "WPN-002",
    name: "RPG-29",
    category: "Weapon",
    catalog_type: "Rocket Launcher",
    unit: "2 Inf Bn",
    blr_count: 1,
    ber: false,
    description: "105mm tandem-warhead launcher, grip assembly BLR",
    status: "pending",
  },
  {
    catalog_no: "WPN-003",
    name: "SPG-9",
    category: "Weapon",
    catalog_type: "Recoilless Gun",
    unit: "1 AT Coy",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "73mm recoilless gun, tripod mounted",
  },
  {
    catalog_no: "WPN-004",
    name: "B-10 RCL",
    category: "Weapon",
    catalog_type: "Recoilless Gun",
    unit: "2 AT Coy",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "82mm recoilless rifle",
  },
  {
    catalog_no: "WPN-005",
    name: "M203",
    category: "Weapon",
    catalog_type: "Grenade Launcher",
    unit: "3 Inf Bn",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "40mm under-barrel grenade launcher",
  },
  {
    catalog_no: "WPN-006",
    name: "AGS-17",
    category: "Weapon",
    catalog_type: "Grenade Launcher",
    unit: "4 Inf Bn",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "30mm automatic grenade launcher",
  },
  {
    catalog_no: "WPN-007",
    name: "L16 81mm Mortar",
    category: "Weapon",
    catalog_type: "Mortar",
    unit: "1 Mort Pl",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "81mm medium mortar, range 5600m",
  },
  {
    catalog_no: "WPN-008",
    name: "M120 120mm Mortar",
    category: "Weapon",
    catalog_type: "Mortar",
    unit: "2 Mort Pl",
    blr_count: 1,
    ber: false,
    description: "120mm heavy mortar, baseplate crack BLR",
    status: "pending",
  },
  {
    catalog_no: "WPN-009",
    name: "M224 60mm Mortar",
    category: "Weapon",
    catalog_type: "Mortar",
    unit: "3 Mort Pl",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "60mm lightweight mortar, range 3490m",
  },
  {
    catalog_no: "WPN-010",
    name: "Milan ATGM",
    category: "Weapon",
    catalog_type: "Anti-Tank Missile",
    unit: "1 AT Coy",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "Wire-guided anti-tank missile system",
  },
  {
    catalog_no: "WPN-011",
    name: "SA-7 Grail",
    category: "Weapon",
    catalog_type: "SAM",
    unit: "1 ADA Bty",
    quantity: 1,
    blr_count: 0,
    ber_count: 0,
    description: "Man-portable surface-to-air missile",
  },
  {
    catalog_no: "WPN-012",
    name: "Stinger FIM-92",
    category: "Weapon",
    catalog_type: "SAM",
    unit: "2 ADA Bty",
    blr: false,
    ber_count: 1,
    description: "MANPADS, seeker head BER — unrecoverable",
    status: "pending",
  },
];

// ── Seed functions ─────────────────────────────────────────────────────────────

export async function seedItems(): Promise<void> {
  console.log(`Seeding ${RAW_ITEMS.length} items...`);
  for (const item of RAW_ITEMS) {
    const { status: itemStatus, ...rest } = item as typeof item & {
      status?: string;
    };
    await addDoc(collection(db, ITEMS_COL), {
      ...rest,
      status: itemStatus ?? "active",
      blr_count: 0,
      ber_count: 0,
      unservicable_count: 0,
      lost_count: 0,
      description: "",
      image: null,
      created_at: serverTimestamp(),
    });
  }
  console.log("Items seeded successfully.");
}

export async function seedLoads(): Promise<void> {
  console.log(`Seeding ${RAW_LOADS.length} loads...`);
  for (const load of RAW_LOADS) {
    const { status: loadStatus, ...rest } = load as typeof load & {
      status?: string;
    };
    await addDoc(collection(db, LOADS_COL), {
      ...rest,
      image: null,
      quantity: (rest as Record<string, unknown>).quantity ?? 1,
      blr_count: (rest as Record<string, unknown>).blr_count ?? 0,
      ber_count: (rest as Record<string, unknown>).ber_count ?? 0,
      status: loadStatus ?? "active",
    });
  }
  console.log("Loads seeded successfully.");
}

export async function seedAll(): Promise<void> {
  await seedItems();
  await seedLoads();
  console.log("All seed data written.");
}
